# ==== Feature Extraction Config ====
epoch: 29
#resume: /home/Daniele/codes/videowalk/code/checkpoints/first_run/model_29.pth
data_path: /data1/runs/videowalk/3_3x3_patches_8_frames_100x100_pixels_108-CMA_channel/filelist.txt
device: cuda  # or 'cpu'
model_type: scratch
img_size: 100
clip_len: 8
temp: 0.05  
frame_skip: 1
batch_size: 1
workers: 4
#output_dir: /data1/fig/videowalk/run-1_30-epochs_8k-clips/extracted_features/epoch_29
no_l2: False
remove_layers: ['layer4']
patch_size: [50, 50, 3]
frame_aug: grid
frame_transforms: none